const { SlashCommandBuilder, AttachmentBuilder } = require('discord.js');
const { createCanvas, loadImage } = require('@napi-rs/canvas');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('impostor')
        .setDescription('Generate an impostor result image for a user')
        .setDMPermission(false)
        .addUserOption((option) =>
            option.setName('user')
            .setDescription('The user to check')
            .setRequired(false)
        ),
    async execute(interaction) {
        const target = interaction.options.getUser('user') ?? interaction.user;
        const member = await interaction.guild.members.fetch(target.id).catch(() => null);
        const displayName = member?.displayName ?? target.username;

        await interaction.deferReply();

        const chance = Math.random() * 100;
        const isImpostor = chance <= 5; // 5% chance

        const width = 900;
        const height = 400;
        const canvas = createCanvas(width, height);
        const ctx = canvas.getContext('2d');

        // Background
        ctx.fillStyle = isImpostor ? '#8B0000' : '#2E8B57';
        ctx.fillRect(0, 0, width, height);

        // Avatar
        const avatarUrl = target.displayAvatarURL({ extension: 'png', size: 512, forceStatic: true });
        const avatar = await loadImage(avatarUrl).catch(() => null);
        if (avatar) {
            const ax = 40, ay = 40, as = 320;
            // circular clip
            ctx.save();
            ctx.beginPath();
            ctx.arc(ax + as / 2, ay + as / 2, as / 2, 0, Math.PI * 2);
            ctx.closePath();
            ctx.clip();
            ctx.drawImage(avatar, ax, ay, as, as);
            ctx.restore();
        }

        // Text
        ctx.fillStyle = '#ffffff';
        ctx.textAlign = 'left';
        ctx.font = 'bold 42px sans-serif';
        ctx.fillText(displayName, 400, 110);

        ctx.font = '28px sans-serif';
        ctx.fillStyle = '#f0f0f0';
        ctx.fillText(`Chance: ${chance.toFixed(2)}%`, 400, 160);

        ctx.font = 'bold 64px sans-serif';
        ctx.fillStyle = '#ffffff';
        const resultText = isImpostor ? 'IMPOSTOR' : 'NOT IMPOSTOR';
        ctx.fillText(resultText, 400, 260);

        // small footer
        ctx.font = '18px sans-serif';
        ctx.fillStyle = '#ffffff';
        ctx.fillText('Generated by Tempus Bot', 400, 340);

        const buffer = canvas.toBuffer('image/png');
        const attachment = new AttachmentBuilder(buffer, { name: `${target.username}-impostor.png` });

        await interaction.editReply({ files: [attachment] });
    }
};
